name: extended_masked_text
description: A small set of custom TextEditingControllers that allows masked text inputs for flutter apps
version: 2.3.1
homepage: https://github.com/LeandroNovak/extended_masked_text

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
